package org.darkmentat

import org.telegram.telegrambots.meta.api.interfaces.BotApiObject
import org.telegram.telegrambots.meta.api.methods.BotApiMethod
import org.telegram.telegrambots.meta.api.methods.send.SendMessage
import org.telegram.telegrambots.meta.api.objects.Update
import org.telegram.telegrambots.meta.bots.AbsSender

class AugmentedRealityCyberpunkCityHandler(
    private val sender: AbsSender
): Handler {

    val downtown = listOf(
        "Pharmacy",
        "Pharmacy",
        "Consumer Electronics",
        "Consumer Electronics",
        "Art Dealer or Gallery",
        "Auto or Robotics Repair",
        "Storage Units or Warehousing",
        "Storage Units or Warehousing",
        "Storage Units or Warehousing",
        "Legal Firm",
        "Religious Building",
        "Religious Building",
        "Capsule Hotel",
        "Capsule Hotel",
        "Data Storage",
        "Low Rent Housing Project",
        "Low Rent Housing Project",
        "Low Rent Housing Project",
        "Grocery Store or Hypermarket",
        "Grocery Store or Hypermarket",
        "Elevated Rail or Road Overpass",
        "Fast Food Franchise",
        "Fast Food Franchise",
        "Fast Food Franchise",
        "Police Precinct",
        "Police Precinct",
        "School or College",
        "Government Building",
        "Government Building",
        "Garage or Parking Block",
        "Body Augmentation Clinic",
        "Body Augmentation Clinic",
        "Body Augmentation Clinic",
        "Luxury Apartments",
        "Luxury Apartments",
        "New Media Company",
        "New Media Company",
        "Industrial",
        "Industrial",
        "Security Tech",
        "Vehicle Showroom",
        "Vehicle Showroom",
        "Fashion Boutique",
        "Fashion Boutique",
        "Commercial Cybernetics",
        "Commercial Cybernetics",
        "Commercial Cybernetics",
        "Mall",
        "VRcade",
        "Gym",
        "Leisureplex",
        "Leisureplex",
        "Apartment Block or Hab Stack",
        "Apartment Block or Hab Stack",
        "Apartment Block or Hab Stack",
        "Apartment Block or Hab Stack",
        "Apartment Block or Hab Stack",
        "Nightclub",
        "Nightclub",
        "Nightclub",
        "Underpass",
        "Hotel",
        "Hotel",
        "Hotel",
        "Ripperdoc",
        "Ripperdoc",
        "3D Print Fabrication",
        "3D Print Fabrication",
        "Courier or Bulk Transport Company",
        "Courier or Bulk Transport Company",
        "Bar",
        "Bar",
        "Bar",
        "Restaurant",
        "Restaurant",
        "Pop-Up Market",
        "Pop-Up Market",
        "Coffee Shop",
        "Coffee Shop",
        "Taxi Firm",
        "Pocket Park",
        "Suburban Housing",
        "Suburban Housing",
        "Movie Theatre",
        "Weapons Tech or Sales",
        "Multi-Level Car Park",
        "Multi-Level Car Park",
        "Bank",
        "Antiques"
    )

    val buildingFeatures = listOf(
        "Extreme Security Protocols",
        "Decrepit And Rundown",
        "Graffitipocalypse/Street Art Heavy",
        "Obvious Gang Turf (see P26)",
        "Back Room Brothel",
        "Newly Renovated",
        "Unusually Busy",
        "Empty/Quiet",
        "Inadequate Security",
        "High Tech Equipment",
        "Abandoned Edifice",
        "Repurposed As... (drop Again)",
        "Front For Corporate Activity (see P22)",
        "Front For Criminal Activity",
        "Hidden Squatters",
        "Obscured By Ad Screens (see P15)",
        "‘Grown’ By Nanites",
        "Incomplete",
        "Self Sufficient",
        "Crumbling Cheapcrete",
        "War Zone",
        "Fire Damage",
        "Not A Building, But Mobile",
        "Elaborate Balconies",
        "Years Of Clumsy Modification",
        "For Sale/To-let",
        "Bright Emoji Glyphs And Graphics",
        "Reinforced For Repair Work",
        "Extremely Leaky",
        "Gothic Style",
        "Chic And Minimalist",
        "Brutalist",
        "Encased In Plastic Siding",
        "Labyrinthine",
        "Skywalks To Other Buildings",
        "Industrial Style",
        "Anti-Drone System",
        "Nano Immune System",
        "People Queue To Enter",
        "Well Guarded",
        "AI Guardian",
        "Ar Heavy (see P17)",
        "Selective Access",
        "Buggy Security Net (see P43)",
        "Taken Over By Junkies",
        "Foreign Ghetto",
        "Sweatshop Conditions",
        "Utilised Solely For Storage",
        "Veiled Behind Polymer Sheeting",
        "All Windows Damaged",
        "External Utilities",
        "Extensive Solar Grid And Fog Catchers",
        "Bad Epoxy Repairs",
        "Unpleasant Micro-Climate",
        "Infested With Rogue Remotes",
        "Self Aware",
        "Cellular Black Hole",
        "Mainly Populated By Hoarders",
        "Accumulated Trash Heaps",
        "Unusual Smell (see P12)",
        "Very Few Working Lights",
        "A Riot Of Satellite Dishes",
        "Very Noisy Utilities",
        "Catastrophically Polluted",
        "Unfinished Extension Or Empty Levels",
        "Permadamp",
        "Legacy Infrastructure (see P11)",
        "Bad Wiring; High EMF; Black Outs",
        "Patrolled By Hired Rent-A-Cops (see P29)",
        "Aggressively Enforced No-Parking Zone",
        "Windows Boarded With Opaque Acrylic",
        "Main Entrance Out Of Order",
        "Several Trashed Cars Out Front",
        "Being Audited By Fanatical City Inspectors",
        "Wind Tunnel",
        "Tinted Glass And Carbon Nano-Tubes",
        "Homeless Magnet",
        "Shakes When Trucks Pass",
        "Completely Automated",
        "Exotic/Foreign Architecture",
        "Obvious Corporate Sponsor",
        "Endorsed By Celebutant",
        "Promotes Religion",
        "Independent Nation State",
        "Family Owned",
        "Scheduled For Demolition",
        "Rat Or Roach Problem",
        "Security Camera Overkill",
        "A Crime Scene",
        "Target Of Net Terrorism",
        "Malfunctioning Incessant Alarm",
        "Slowly Collapsing Or Subsiding",
        "Under Surveillance",
        "Enforced No Fly Zone",
        "Prone To Flooding",
        "Ecologically Sound; No Carbon Footprint",
        "Popular With Particular Subculture",
        "Totally Sterile",
        "Extensive Drone Docks",
        "Causes Sickness (see P10)"
    )

    val smells = listOf(
                "Cigarette Smoke",
                "Cheap Perfume",
                "Expensive Cologne",
                "Exhaust Fumes",
                "Stale refuse",
                "Urine",
                "Burning Plastic",
                "Vomit",
                "Ash",
                "Acrid Chemicals",
                "Cordite",
                "Blood",
                "Wet Hair"
                //todo full list
    )

    val sounds = listOf(
        "Building Alarm",
        "Barking Dogs",
        "Incoherent Shouting",
        "A Single Gunshot",
        "Ventilation System",
        "Car Doors Slamming",
        "Loud Television",
        "Children",
        "Aerocar Overhead",
        "Catchy Corporate Jingle",
        "The Screech Of Tires"
        //todo full list
    )


    override fun processDirect(update: Update): BotApiMethod<out BotApiObject>? {
        println("SEND: cyberpunk downtown")

        val msg = update.message?.text?:return null

        val res = "${downtown.random()}\n_${buildingFeatures.random()}_\n_${buildingFeatures.random()}_\n\n" +
                  "${downtown.random()}\n_${buildingFeatures.random()}_\n_${buildingFeatures.random()}_\n\n" +
                  "${downtown.random()}\n_${buildingFeatures.random()}_\n_${buildingFeatures.random()}_\n\n" +
                  "${downtown.random()}\n_${buildingFeatures.random()}_\n_${buildingFeatures.random()}_\n\n" +
                  "${downtown.random()}\n_${buildingFeatures.random()}_\n_${buildingFeatures.random()}_\n\n" +
                   "Smells like ${smells.random()} and ${smells.random()}, Sound ${sounds.random()} and ${sounds.random()}"

        return SendMessage()
            .setChatId(update.message.chatId)
            .setText(res)
            .enableMarkdown(true)
    }
}