package org.darkmentat

import org.telegram.telegrambots.meta.api.interfaces.BotApiObject
import org.telegram.telegrambots.meta.api.methods.BotApiMethod
import org.telegram.telegrambots.meta.api.methods.send.SendMessage
import org.telegram.telegrambots.meta.api.methods.updatingmessages.EditMessageText
import org.telegram.telegrambots.meta.api.objects.CallbackQuery
import org.telegram.telegrambots.meta.api.objects.Update
import org.telegram.telegrambots.meta.api.objects.replykeyboard.InlineKeyboardMarkup
import org.telegram.telegrambots.meta.api.objects.replykeyboard.ReplyKeyboardMarkup
import org.telegram.telegrambots.meta.api.objects.replykeyboard.buttons.InlineKeyboardButton
import org.telegram.telegrambots.meta.bots.AbsSender
import kotlin.random.Random

class NameGeneratorHandler(
    private val sender: AbsSender,
    private val keyboardMarkup: ReplyKeyboardMarkup
): Handler {

    override val callbackCommands = listOf(
        "/random_name",
        "/random_name_eng",
        "/random_name_fra",
        "/random_name_ger",
        "/random_name_jap",
        "/random_name_chi",
        "/random_name_exotic"
    )

    //Generated by https://www.fantasynamegenerators.com/

    private val englishMale = listOf(
        "Norman Dickerson", "Victor Underwood", "Theodore Bridges", "Stuart McLeod", "Ronnie Prince", "Dwight Dickson", "Terrance Barrera", "Luis Larson", "Cristian Chapman",
        "Jacob Moody", "Leonard Blair", "Sylvester May", "Eddie Boone", "Craig Kent", "Darin Carpenter", "Jeffrey Craft", "Angel Alexander", "Danny Wheeler", "Malik Conway",
        "Ricardo Johnston", "Melvin Perkins", "Ed Meadows", "Horace Hodges", "Hubert Freeman", "Nathan Miller", "Floyd Bridges", "Kelly Taylor", "Jamie McKenzie", "Hayden Vincent",
        "Kenneth Key", "Sidney Alston", "Arnold Watson", "Roy Harper", "Wilbur Bartlett", "Dan McGee", "Anthony Whitfield", "Jose Hampton", "Jermaine Conway", "Jonathan Montgomery",
        "Carson Rivera", "Chester Robinson", "Lee McCarty", "Bobby Middleton", "Gene Koch", "Jim Luna", "Benjamin Pierce", "Matthew Hunter", "Brad Norman", "Parker Dickerson",
        "Frank Burns", "Perry Burch", "Douglas Burke", "Samuel Hardy", "Bernard McMillan", "Vincent Massey", "Jose Hopper", "Kenneth Lawrence", "Colin Williamson", "Curtis Mason",
        "John Spence", "Phillip Newman", "Jacob Britt", "Clinton Burch", "Earl Good", "Eric Tate", "Tim Sharp", "Dwayne McKenzie", "Andrew Kidd", "Calvin Richard", "Troy Humphrey",
        "Zac Khan", "Reuben Watts", "Lewis King", "Isaac Gordon", "Owen Foster", "Aydin Rogers", "Eduardo Heath", "Jordan Cash", "Reed Perry", "Guillermo Pope", "Frederick Cunningham",
        "Ewan Cook", "Hayden Hunt", "Jordan Byrne", "Finley Butler", "Iker Hayes", "Markus Peterson", "Kyree Spencer", "Carl Davis", "Gunnar Leblanc", "Riley Phillips", "Ethan Mccarthy",
        "Robert Carr", "Aaron Ryan", "Ben Shaw", "Johnny Bates", "Alexander Diaz", "Khalil Cotton", "Briggs Emerson", "Mayson Brewer", "Jay Newman", "Liam Carr", "Finley Wright",
        "Finley Kennedy", "Bailey Houghton", "Phillip Knox", "Max Rose", "Jaxson Nixon", "Jeffery Lane", "Rylee Gilmore", "Morgan Jenkins", "Joe Young", "Joel Harris", "Robert Marsh",
        "Aidan Carter", "Gideon Mathis", "Shane Cotton", "Gerardo Mercado", "Isiah Head", "Felix Jennings", "Sewel Longton", "Pascoe Lucy", "Leofstan Duncombe", "Percival Twarby",
        "Gabriel Beaumont", "Godric Shotbolt", "Elgar Brocksby", "Hervey Mowfurth", "Reginald Wynter", "Augustin Drayton", "Bernard Tilghman", "Lewin Flower", "Andrew Morecote",
        "Denis Kyrkeby", "Sampson Gaynesford", "Siward Fayneman", "Elric Verney", "Marmaduke Kottow", "John Kydwelly", "Oswyn Obson", "Lawrence Launceleyn", "Nicolas Champneys",
        "Athelstan Eglisfelde", "Daniel Brinckhurst", "Alexander Hansart", "Algar Latham", "Miles Darcy", "Wulfwin Whalley", "Elyas Nele", "Avery Savill", "Nigel Marsham",
        "Geoffrey Lymsey", "Asketil Malemayns", "Leofric Higate", "Christopher Ryall", "Alfred Chetwoode", "Adrian Loveney", "Ailwin Goodenouth", "Giles Merstun", "Rolf Stanwix",
        "Randall Helme", "Asketil Gosebourne", "Anthony Switte", "Wulsi Northwoode", "Norman Crane", "Ailwin Clitherow", "Ulf Gasper", "Thurstan Perot", "Eustace Langham", "Elric Shiveley"
    )
    private val englishFem = listOf(
        "Pearl Harrell", "Loretta Bates", "Theresa Walters", "Deborah Rose", "Doreen Holloway", "Amanda Cain", "Desiree Meyer", "Kristen Fletcher", "Diana House", "Kaitlin Bond",
        "Rosalie Mueller", "Lucille Bruce", "Donna Frye", "Naomi Tate", "Irene Glover", "Louise Lott", "Felicia Wilkinson", "Ashlee Johns", "Marisa Griffin", "Courtney Combs",
        "Matilda Malone", "Julia James", "Mildred Brewer", "Elaine Bryan", "Marjorie Frye", "Sonya Dorsey", "Connie George", "Stacie Pearson", "Yesenia George", "Karen Carr",
        "Delores Gordon", "Marilyn Hamilton", "Deborah Clemons", "Faye Payne", "Betty Steele", "Marlene Pena", "Annette Hobbs", "Sonia Richards", "Lilly Morris", "Giselle Hopkins",
        "Anita Harris", "Maria Bradford", "Dolores Duffy", "Ann McFarland", "Elaine Owens", "Janice Oliver", "Autumn Larson", "Rebecca Blackwell", "Jordyn Callahan", "Katherine Reed",
        "Hollie Duncan", "Natasha Marsh", "Libby Willis", "Matilda Palmer", "Sara Pearson", "Kyra Morin", "Mae Ellison", "Dakota Morrison", "Callie Gamble", "Myah Burks", "Esme Scott",
        "Bella Booth", "Rose Riley", "Lexi Reynolds", "Lacey Kaur", "Ryleigh James", "Jamie Hartman", "Kristina Snow", "Cadence Craig", "Mikayla Simmons", "Katie Clarke", "Lydia Wilson",
        "Nicole Taylor", "Evelyn Atkinson", "Eloise Williamson", "Jaylee Byers", "Alexandra Vinson", "Aisha Barry", "Emmaline Crawford", "Alia Camacho", "Isobel Moore", "Aimee Gardner",
        "Poppy Perry", "Abbie Sutton", "Isobel Bell", "Mariyah Shepard", "Nadia Marsh", "Macy Davis", "Elsie Fry", "Taraji Bowman", "Maya Mcdonald", "Maria Edwards", "Lauren Barker",
        "Demi Matthews", "Maisie Brooks", "Tenley Stephenson", "Eva Roberts", "Teresa Alexander", "Adeline Matthews", "Ingrid Weber", "Isabel Switte", "Godiva Abell", "Iseult Courtenay",
        "Ailith Stone", "Hannah Fitzherbert", "Rose Bedell", "Lovechild Bernewelt", "Saelova la Penne", "Ismenia Barton", "Jenefer Gardyner", "Godusa Haye", "Lucy Barantyn", "Clementia Stylle",
        "Saegifu Hatteclyff", "Elizabeth Bosby", "Martha Kottow", "Helen Sulyard", "Felicia Albyn", "Albreda Erewaker", "Eve Moryet", "Godith Seymour", "Florence Chechester", "Milda Hancock",
        "Godlefe Stone", "Margery Holbrook", "Lucy Aynesworth", "Engelise Bartelot", "Maud Fraunces", "Parnell Whalley", "Preciosa Asger", "Iva Notfelde", "Joyce Fulmer", "Ida Alleine",
        "Turgiva Hornebolt", "Thomasine Tedcastle", "Barbara Gardyner", "Ivette Boddinham", "Maud Sayer", "Adeline Blenerhayset", "Emma Geddyng", "Mabel Harbird", "Wenthelen Bladwell",
        "Ruth Aldebourne", "Parnell Ruggeweyn", "Grace Wallace", "Torilda Fogg", "Cassandra Fleming", "Charity Sacheverell", "Euphemia Narbrige", "Felicia Leynham", "Leia George",
        "Zara Lawrence", "Rowan Shaw", "Keira Marsh", "Rosalie Butler", "Ariella Roberts", "Autumn Barnes", "Aliyah Hayes", "Evie Kennedy", "Maria Phillips", "Melissa Hawkins",
        "Lana Fraser", "Olivia-Rose Bailey", "Natalia Mcdonald", "Talia Collins", "Poppy Parry", "Madison Jones", "Maddison Richards", "Nyla Lawson", "Hanna Griffiths", "Jessica Sharp",
        "Fern Baker", "Bianca Foster", "Leila Martin", "Amalia White", "Poppy Lee", "Annabelle Wilkinson", "Josie Sharp", "Izabella Armstrong", "Alaya Chapman", "Helena Ross",
        "Scarlett Marshall", "Diana Newman", "Stella Jackson", "Pearl Ross", "Maisy Cooper", "Eva Hudson", "Alexia Marsh", "Beatrice Ball", "Beatrix Hunt", "Adriana Carter",
        "Luna Fox", "Dakota Simpson", "Macie Harper", "Lacie Kaur", "Lacey Murphy", "Ciara Bradley", "Zoe Wilson", "Aleena Gill", "Kiara Graham"
    )

    private val frenchMale = listOf(
        "FrenchErnest Barthélemy", "Edgar Rigal", "Charles Chaufourier", "Jules Ouvrard", "Aymeric Bonnel", "Josselin Compere", "Valéry Gérin", "Bruno Cordonnier", "Rodolphe Aliker",
        "Marius Portier","Alexis Abadie", "Pierre Vaganay", "Robin Gide", "Thibaud Jacquemoud", "Christian Bachelet", "Barthélemy Chéron", "Remy Colbert", "Jean-Christophe Cormier",
        "Grégory Lussier", "Jean-Jacques Barnier", "Nicolas Héroux", "Amadou Carrel", "Olivier Leroux", "Jean-Jacques Boulanger", "Louis Maret", "Stéphane Trottier", "Enzo Bertillon",
        "Hervé Brousseau", "Gilbert Matthieu", "Roch Vaillancourt", "Eugène Auclair", "Dominique Touchard", "Ludovic Chauveau", "Julien Beauvau", "Grégory Besson", "Léo Gicquel",
        "Julien Girault", "Kevin Baugé", "Henry Garreau", "Bruno Jaccoud", "Basile Figuier", "François Passereau", "Jean Micheaux", "Léo Auch", "Maxime Barthélemy", "Patrice Bourdon",
        "Philibert Brunelle", "Marc Fresnel", "Régis Grandis", "Porthos Lavaud", "Gaétan Lecocq", "Dimitri Bourgeois", "Basile Brian", "Gaëtan Leroux", "Christopher Arceneaux",
        "Ernest Deschanel", "Rodolphe Sardou", "Joseph Bechard", "Léon Castex", "Geoffroy Montgomery", "Augustin Demaret", "Edgar Rodier", "Yves Béliveau", "Bastien Benett",
        "Édouard Chaufourier", "Julien Mossé", "Denis Halphen", "Hubert Magnier", "Gervais Chappuis", "Samuel Fouquet", "Lucas Laflèche", "Damien Azaïs", "Jean-Christophe Ballouhey"
    )

    private val frenchFem = listOf(
        "Gaëtane Manaudou", "Manon Dupuis", "Héloïse Cazal", "Solange Masson", "Dominique Beaugendre", "Christelle Saunier", "Stéphane Raoult", "Anne-Marie Gicquel", "Léonie Celice",
        "Carla Chardin", "Godeliève Devereux", "Léonie Emmanuelli", "Éliane Bazalgette", "Amandine Gauthier", "Marie-Thérèse Toussaint", "Jade Béliveau", "Violaine Batteux",
        "Annick Lacan", "Lise Larousse", "Ilonna Botrel", "Simone Grandis", "Sonia Beaumanoir", "Olivia Thibodeaux", "Laetitia Carpentier", "Julie Boulet", "Clélie Gaudin",
        "Antoinette Bonnel", "Anita Barbeau", "Anne Nee", "Victoria Bonnel", "Chloé Rapace", "Mathilde Édouard", "Bérengère Gilson", "Albertine Sharpe", "Leila Baumé",
        "Marguerite Colbert", "Godeliève Jacquemin", "Sabrina Bethune", "Auriane Bettencourt", "Edmée Bousquet", "Roxane Piaget", "Charlène Duret", "Joséphine Chastain",
        "Tiphaine Corriveau", "Pierrette Chapuis", "Barbe Beaumont", "Clémentine Charbonneau", "Rosalie Barbet", "Jeannine Derocles", "Maïté Manoury", "Céline D'Aboville",
        "Lucrèce Plantier", "Marie-José Guilloux", "Joséphine Boudreaux", "Bérénice Gérin-Lajoie", "Marielle Lucroy", "Séverine Boudier", "Emmeline Jacquemin", "Paola Cartier",
        "Nicolette Brugière", "Roseline About", "Ophélie Beaugendre", "Lisette Duchamp", "Claudette Lahaye", "Alphonsine Sharpe", "Nadia Auch", "Lucrèce Mossé", "Julia Donnet",
        "Godeleine Kléber", "Constance Naudé", "Corinne Chappelle", "Mélodie Gavreau", "Marie-Noëlle Bechard", "Annie Lalande", "Haydée Demaret", "Ségolène Duclos", "Pauline Pasteur",
        "Eugénie Cormier", "Denise Descombes", "Laëtitia Baschet", "Éléonore Boudier", "Clélie Desmarais", "Godeliève Rouanet"
    )

    private val germanMale = listOf(
        "Markus Wassermann", "Isaak Hauschka", "Marius Furtwängler", "Kilian Wall", "Jochen Taussig", "Reinhard Bärwald", "Bernhard Steinberg", "Benedict Bluhm", "Ekkehard Kachel",
        "Jörn Grisbaum", "Alois Stangl", "Tillmann Scharwenka", "Alfred Hannawald", "Stanislaus Adorf", "Harri Stosch", "Viktor Köstler", "Willi Honigsberg", "Ferdinand Gegenbauer",
        "Johann Hasselbach", "Henny Hegeler", "Phillipp Stock", "Sigmund Rösler", "Silvester Honigmann", "Theophilus Ludecke", "Thaddäus Escherich", "Thorwald Neuer", "Leo Weitz",
        "Justin Löw", "Heribert Hergenröther", "Matthias Stosch", "Luca Wittgenstein", "Albin Prager", "Lennart Rosenhain", "Timon Herdrich", "Benedikt Schoff", "Vinzenz Heuberger",
        "Alfred Heuser", "Marco Strassmann", "Arnold Ohlendorf", "Linus Josten", "Bruno Bechtel", "Victor Behm", "Marcel Dehnert", "Dieter Strauss", "Adelger Wagenknecht", "Edgar Distler",
        "Vinzenz Mencken", "Ägid Deutscher", "Sebastian Holderbaum", "Tilman Holderbaum", "Helmut Grimminger", "Lutz Grebel", "Ferdinand Weininger", "Elia Weschler", "Dan Buch", "Brian Fisker",
        "Nick Laustsen", "Thorvald Høyer", "Freddy Juul", "Anders Graversen", "Oluf Holm", "Mikael Vilhelmsen", "Gunnar Thøgersen", "Elmer Hansen", "Marcus Johannesen", "Kim Jansen",
        "Michael Johansen", "Adam Asmussen", "Nick Høyer", "Jonas Skaarup", "Jim Bjerg", "Michael Hviid", "Thyge Damsgaard", "Ivan Bendixen", "Rolf Nygaard", "Nikolaj Elkjær", "Vagn Ebbesen",
        "Ernst Thygesen", "Eskild Eriksen", "Germund Hartmann", "Elo Kofoed", "Hugo Fuglsang", "Noah Clausen", "Ernst Laugesen", "Julian Rainer", "Martin Albert", "Nino Schifter",
        "Jannik Baeder", "Lukas Diemberger", "Niklas Steiner", "Johannes Hundertwasser", "Fabio Bernhard", "Jamie Moser", "Josef Austen", "Peter Bemelmans", "Robin Kuhn", "Fabian Nalder",
        "Niklas Neurath", "Ben Lehner", "Stefan Wimmer", "Philipp Muster", "Oliver Haspel", "Adam Kasper", "Matthias Loos", "Jonathan Auer", "Julian Adler", "Adam Loos", "Lenny Leitner",
        "Luca Mahler", "Ben Steiner", "Linus Fiser", "Christian Schmid", "Dominik Berger", "Louis Lanner"
    )

    private val germanFem = listOf(
        "Marike Bärwald", "Hanne Buchman", "Angela Hering", "Marga Haber", "Petra Neuhaus", "Madleen Kautz", "Natascha Reichenau", "Rafaela Wittke", "Luise Trausch", "Susanna Schroth",
        "Sibylle Lobe", "Anne Sperl", "Bettina Riemenschneider", "Miriam Auernheimer", "Louise Habich", "Edda Ketterer", "Gretel Sauerbruch", "Adelheid Maier", "Fanny Kistler", "Lotte Ulmer",
        "Leonie Wenz", "Rose Frisch", "Katja Metze", "Mia Harnisch", "Margret Tetzlaff", "Cecilie Schnell", "Monica Pruefer", "Siglind Wölfflin", "Traute Hecht", "Mara Lettmann", "Sofia Bechtold",
        "Sabrina Apfelbaum", "Mia Ehrenfeld", "Yasmin Schiller", "Angela Ahle", "Ronja Kehrer", "Lotte Herder", "Madeleine Hagmann", "Sina Vetter", "Pia Honig", "Valentina Hönigswald",
        "Mareike Altschul", "Gunda Reichleitner", "Catrin Bennewitz", "Felicitas Röhr", "Layla Lehning", "Marga Schott", "Rosa Dedekind", "Brunhild Bahr", "Esther Rausch", "Rafaela Schönfinkel",
        "Ottilie Gilger", "Agnes Wiedemann", "Leonie Detmold", "Greta Hausle", "Emelie Albert", "Stella Bemelmans", "Carina Bachmann", "Julia Vogl", "Clara Scherer", "Paulina Fichter",
        "Mona Manz", "Amina Frankenberger", "Helena Burger", "Natalie Hausner", "Celine Puchner", "Lara Wagner", "Anika Werner", "Carolina Bruckner", "Alexandra Pichler", "Milena Mayr",
        "Amelie Fuchs", "Anna Berger", "Rebecca Widrich", "Sophia Burger", "Carolina Boltzmann", "Naomi Dorn", "Melissa Fessler", "Livia Fritzl", "Katharina Weingartner", "Lisa Hoferle",
        "Elina Senefelder", "Emilia Weinheber", "Selina Wach", "Dagmar Skovgaard", "Iben Mortensen", "Kirsten Vestergaard", "Bitten Graversen", "Edith Kofod", "Jasmin Eskildsen", "Oline Hoffmann",
        "Elin Ludvigsen", "Anna Fabricius", "Magda Hedegaard", "Kate Buch", "Else Hansen", "Jenny Svenningsen", "Olivia Bay", "Dorthea Bruun", "Sonja Frost", "Karin Kristensen", "Solvej Nissen",
        "Susanna Michelsen", "Katja Rohde", "Tine Jeppesen", "Lene Pedersen", "Malene Isaksen", "Birthe Brink", "Emma Truelsen", "Karin Nygaard", "Ann Kjærgaard", "Lise Johnsen", "Karoline Kruse"
    )

    private val exoticMale = listOf(
        "Putra Adi Sutedja", "Dwi Hengki Kurniawan", "Willy Huang Fu", "Sieto Yanlin", "Waseem Silahooij", "Nahum Ndruru", "Thomas Harefa", "Rufus Silalahi", "Bambang", "Kuwat",
        "Susila Johan Kartawijaya", "Hendri Suparman Oesman", "Syariel Hung", "Wangsa Peng", "Haaroon Taihuttu", "Philip Berampu", "Elihu Simandalahi", "Ananias Brahmana", "Sukarno",
        "Dwi", "Karan Tur", "Giansh Basi", "Ratan Garhar", "Hanspal Lahar", "Dilawar Kanon", "Varinderpal Kapoor", "Mohanbir Kalirai", "Amun Tiwana", "Sherbahadur Rattol", "Armaan Kator",
        "Sabahat Chandiramani", "Saeed Keswani", "Qaseem Raheja", "Talal Ratwani", "Ashish Kukreja", "Umayr Dayani", "Safiyy Udeshy", "Rais Relwani", "Pradeep Khilnani", "Safiy-Allah Sainani",
        "Ilsat Abdullin", "Fejzulla Yusupov", "Ilşat Gainutdin", "Çıñğız Borhan", "Timerkhan Dinov", "Eduard Galimov", "Azat Utiashev", "Toktamish Bronson", "Tahir Mamashev", "Röstäm Gimatov",
        "Mvuseselo (Revival)", "Phesheya (Overseas)", "Ingiyab (Serpent)", "Nsizwa (Young Man)", "Qiniso (Truthful)", "Thandoluhle (Good Love)", "Mandlakhe (Strength / Power / His Efforts)",
        "Phila (Good Health)", "S'bonele (Example)", "MusaweNkosi (Having The Grace Of God)", "Bongani (Be Thankful, Grateful )", "Zenzele (Do For Self)", "Izagala (Stick)",
        "Sinenhlanhla (We Have Luck)", "Gebhuza (Slashing Warrior)", "Thuthuka (Become A Better Person)", "Mhambi (Traveler)", "Sibakabaka (Sky, Blue Sky)", "Gijimi (Professional Runner, Messenger)",
        "Azisa (Honour, Esteem, Pride)", "Yoliyamanitzin", "Ohtli", "Yayauhqui", "Ixtli", "Ixtli", "Azcalxochipan", "Sacnen", "Zanipalli", "Ihuicama", "Cozamatia"
    )

    private val exoticFem = listOf(
        "Vigsai Wamak", "Sach Binepal", "Livroop Dandi", "Kawaljit Mudhar", "Hamir Dhandsahar", "Marig Tola", "Upaavan Jopo", "Harleen Semi", "Alam Jathol", "Roop Chaggar", "Simrin Bhalar",
        "Sukhmeet Jurai", "Giaanroop Pandi", "Ajooni Jamra", "Yuvleen Jawa", "Simar Gorah", "Garima Kundi", "Adarshpreet Sangrota", "Rangjot Chaggar", "Manat Wanwar", "Kamaliyah Surtani",
        "Hayfa Sidhwani", "Shamshad Wadhwa", "Kaneez Lachhwani", "Sahirah Lohi", "Najm Parwani", "Tabalah Furtani,", "Pooja Ramrakhiani", "Rahimah Nainani", "Leena Amamani", "Buqayrah Ajbani",
        "Karam Hassani", "Benazir Nebhrajani", "Sabburah Dialani", "Tina Masand", "Taqiyah Panjwani", "Thaminah Parpyani", "Basimah Chatppar", "Faqirah Bajaj", "Rahilah Dingreja",
        "Chulpan Gimayeva", "Firdausa Abrashitova", "Gölnara Khusainova", "Albinä Gimatova", "Märziya Fakhrutdinova", "Roza Sagdeeva", "Läysän Waxitova", "Firaya Ichmouratova",
        "Gusel Shafigulina", "Xäliulla Nabiullina", "Zintwezinhle (Beautiful Things)", "Zondlile (Nourished Herself)", "Nokulunga (Faithfulness)", "Nobuntu (Kindness)", "Thandazile (Have Prayed)",
        "Enezezelo (Addition)", "Ethwasa (Start Anew)", "Cwazimula (Shine Brightly)", "Nozipho (Mother Of Gifts)", "Ntokozo (Joy, Happiness)", "Dandalaza (In The Open)", "Dandalaza (In The Open)",
        "Icici (Earring)", "Lethiwe (She's Been Brought)", "Dumile (Renowned)", "Zodwa (Girls Only)", "Gabisile (She, Who We Can Show Off)", "Makhosazana (Princess)", "Khethiwe (Chosen)",
        "Uluthando (She Is Love)", "Xilonen", "Citlali", "Patli", "Zyanya", "Etalpalli", "Toltecatecol", "Necualal", "Pacali", "Itotli", "Pametl", "Yaretzi", "Yaretzi", "Xoco", "Momoztli",
        "Teicuih", "Huitzillin", "Momozcali", "Tlacaetic", "Iuitic", "Matlalilaloni", "Bethari Bulan Hermawan", "Glenna Ade Rachman", "Onggano Ai", "Wendi Shuang", "Jet Octovian",
        "Talitha Bangkiang", "Judith Sigalingging", "Chloe Manalu", "Dwi", "Wangi", "Shinta Dewi Atmadjaja", "Ratna Ida Tan", "Gunawan Song", "Tanuseputro Ju", "Karen Tubun", "Mara Sinukaban"
    )

    private val japaneseMale = listOf(
        "Higashi Noriyori", "Shiro Togai", "Tabata Keishi", "Takano Eisen", "Tengan Norihide", "Kinjo Kenzaburo", "Ando Gengyo", "Umesaka Korechika", "Takahashi Takuma", "Hayashi Toyoshige",
        "Koshikawa Hiroharu", "Sugai Koin", "Shinobu Gyukudo", "Kirigaya Kyoden", "Yajima Yoshitake", "Tsutsumi Takeshi", "Toda Hanshiro", "Yaguchi Takamori", "Utsumi Heihachiro", "Yamabe Jomei",
        "Oyakawa Fujimaro", "Hamano Mitsuhide", "Yamaha Akinari", "Chijimatsu Yasuhiro", "Asari Dai", "Yoshikawa Jo", "Wakamura Kakuzo", "Hatanaka Kaemon", "Otani Toshi", "Baisho Hisayuki",
        "Shiraki Norishige", "Gima Shinsui", "Kuwahara Mikio", "Narita Sukeyasu", "Matsutani Masaaki", "Tani Sukenobu", "Narita Rai", "Katsuragi Tsumemasa", "Sawachika Yosai", "Izumo Seison",
        "Kawakami Morichika", "Honda Iemoto", "Fujii Morinari", "Azai Tokiuji", "Yoshida Kiyoharu", "Kira Yasutane", "Tokudaiji Yoriharu", "Satomi Tomosue", "Mori Toshinobu",
        "Kitabatake Michitomo", "Furuta Naoaki", "Ando Tomotoshi", "Tokugawa Hikomoro", "Yagyuu Yoshimochi", "Satou Masatada", "Kumagaya Yoriuji", "Tozawa Masatoshi", "Gamou Mochikage",
        "Sen Hirayoshi", "Morikawa Kiyotame", "Sen Arishige", "Nomiya Shigetane", "Kawabe Chikamitsu", "Shimokoube Akiyuki", "Fujioji Hikonaka", "Nagai Suketsune", "Saigou Moriyuki",
        "Taira Tadakatsu", "Fujioka Morikane", "Nishitouin Ariyasu"
    )

    private val japaneseFem = listOf(
        "Shoji Hairi", "Komuro Chihoko", "Takahara Eire", "Iori Michi", "Onaga Usami", "Matsuyama Maki", "Ishimoto Rumi", "Takaki Yukiko", "Saito Jori", "Kawasaki Hisano", "Uchibayashi Ome",
        "Toyoda Kyoko", "Manaka Inari", "Fujino Sakurako", "Izuhara Machi", "Watanabe Suzuki", "Edamitsu Satoko", "Amari Miliko", "Uchikoshi Echiko", "Takanashi Hisako", "Orio Arei",
        "Hatanaka Oharu", "Samon Ryou", "Sugai Mamiko", "Eto Mine", "Chikae Isuzu", "Konno Naomi", "Sumisu Risu", "Fukuhara Oriana", "Kaneshiro Muika", "Nonaka Nozomi", "Kobashigawa Warabi",
        "Miyaguchi Mamiko", "Amagawa Kiwa", "Miyahara Nayoko", "Kotobuki Eriko", "Matsuoka Yume", "Namba Rie", "Furuya Hatsue", "Tanaka Osami", "Shiro Shungiku", "Kozato Ryu", "Arashiro Yukari",
        "Noyamano Wakuri", "Kuroki Inoue", "Yoshimi Rumi", "Miyasato Michie", "Tezuka Nanako", "Kase Kazashi", "Kojima Isuzu", "Morikawa Oma", "Honomi Tsubo", "Tokugawa Kan", "Ujie Sako",
        "Inagaki Kinu", "Takahashi Den", "Matsui Tan", "Fuji Yura", "Terazawa Tane", "Imai Run", "Karahashi Haru", "Abe Kusushi", "Matsukura Kuu", "Shouni Sawa", "Aso Tsuta", "Kawguchi Ko",
        "Akamatsu Sukeyo", "Sagara Iri", "Tanegashima Kuwa", "Gotou Isano", "Nishina Mutsu", "Miyabe Ume", "Nakajima Naguyo", "Sanada Kaku", "Hirano Yasushi", "Mikumo Komeme", "Nakatomi Hime",
        "Shinmen Koroshi", "Ando Hotsu", "Hirohashi Mata"
    )

    private val chineseMale = listOf(
        "Wan Fu", "Yan Rong", "Shen Kun", "Mo Qiang", "Wei Chang", "Xue Ning", "Ye He", "Xuan Zheng", "Qin Long", "Du Lei", "Shi Tian", "Jia Jun", "Dong Xinyue", "Feng Bao", "Lin Wei", "Xu Hua",
        "He He", "Zi Zheng", "Zhou Guo", "Zhong Bai", "Zhan Shui", "Shen Lim", "Zhang Zexian", "Gao Meng", "Huo Wuhan", "Shi Rong", "Bai Yang", "Pan Jun", "Luo Jin", "Wen Wuying", "Cao Guanting",
        "Xia Zhen", "Chang Liang", "Su Su", "Luo Song", "Zhou Long", "Lian Hanying", "Yu Huan", "Jiang Zhou", "Ye Zhenya", "Uất Tôn Lễ", "Sái Hữu Bình", "Phạm Hoàng Giang", "Trương Hòa Hợp",
        "Đặng Tiến Dũng", "Bạch Tường Nguyên", "Đặng Phúc Lâm", "Dương Trọng Kim", "Bùi Mạnh Nghiêm", "Triệu Việt Khang", "Won Jung-Su", "Hu Young-Gi", "P'aeng Woo-Jin", "Om Il-Seong",
        "Ryang Duck-Young", "Kil Dong-Hyun", "Sa Ji-Hun", "T'an Young-Shik", "Kok Kyung-Gu", "Ah Kyung-Mo", "Won Jung-Su", "Hu Young-Gi", "P'aeng Woo-Jin", "Om Il-Seong", "Ryang Duck-Young",
        "Kil Dong-Hyun", "Sa Ji-Hun", "T'an Young-Shik", "Kok Kyung-Gu", "Ah Kyung-Mo", "Ouk Chamroeun", "Yu Narith", "Duong Bora", "Sen Chakara", "Suy Puthyrith", "Loun Many", "Iv Sothea",
        "Khin Chantrea", "Ung Heng", "Lorn Roth"
    )

    private val chineseFem = listOf(
        "Lian ZhenKang", "Qin Tu", "Yi Huan", "Xiong Xuefeng", "Gu Chao", "Gao Xieren", "Qian Jiang", "Liang Jing", "Lang Lian", "Zeng Yu", "Zi Huan", "Liang Huo", "Lu Zemin", "Zeng Xinya",
        "Pan Hua", "Fang Chun", "Wei Bo", "Yao Guo", "Ma Yun", "Xuan Wuying", "Gu Dai", "Cheng Ah", "Xun Zhenya", "Zhou Yun", "Fu Ju", "Yang Yazhu", "Yu Ling", "Lang My", "Zhuan Li",
        "Ma Hanying", "Võ Gia Khanh", "Nguyễn Xuân Linh", "Đặng Thu Linh", "Bùi Diệp Chi", "Mạch Quỳnh Vân", "Ngô Nhã Trúc", "Trịnh Ðông Tuyền", "Bạch Quỳnh Sa", "Võ Diễm Phương",
        "Bạch Nguyệt Nga", "Kwak Chong-Hui", "Sip Myong-Suk", "Yon Ga-Yun", "Hwangbo Eun-Song", "Hu Yun-Ji", "P'aeng Suh-Hyung", "Myo Ae-Ri", "Kung Eun-Ah", "Ch'ae Yujin", "Jan Jorani",
        "Neak Seyha", "Iem Leakena", "Choem Roumjong", "Phy Pich", "Chea Mony", "Pheng Neary", "Khoun Sikha", "Or Kalliyan", "Dul Maly", "Bun Maly", "Choem Savady", "Chin Kolab", "Sok Sophon",
        "Duong Saley", "Dith Chantrea", "Neak Visna", "Lorn Darareaksmey", "Ma Ary", "Chhit Dara"
    )

    private val inlineReplyKeyboard = InlineKeyboardMarkup().apply {
        keyboard = listOf(
            listOf(
                InlineKeyboardButton().setText("\uD83D\uDD01").setCallbackData("/random_name"),
                InlineKeyboardButton().setText("\uD83C\uDDEC\uD83C\uDDE7").setCallbackData("/random_name_eng"),
                InlineKeyboardButton().setText("\uD83C\uDDEB\uD83C\uDDF7").setCallbackData("/random_name_fra"),
                InlineKeyboardButton().setText("\uD83C\uDDE9\uD83C\uDDEA").setCallbackData("/random_name_ger"),
                InlineKeyboardButton().setText("\uD83C\uDDEF\uD83C\uDDF5").setCallbackData("/random_name_jap"),
                InlineKeyboardButton().setText("\uD83C\uDDE8\uD83C\uDDF3").setCallbackData("/random_name_chi"),
                InlineKeyboardButton().setText("\uD83D\uDDFB").setCallbackData("/random_name_exotic")
            )
        )
    }

    override fun processDirect(update: Update): BotApiMethod<out BotApiObject>? {
        println("SEND:  generate name")

        val d100 = Random.nextInt(100)

        val name = when{
            d100 < 25 -> englishMale.random()
            d100 < 50 -> englishFem.random()
            d100 < 55 -> frenchMale.random()
            d100 < 60 -> frenchFem.random()
            d100 < 65 -> germanMale.random()
            d100 < 70 -> germanFem.random()
            d100 < 75 -> japaneseMale.random()
            d100 < 80 -> japaneseFem.random()
            d100 < 85 -> chineseMale.random()
            d100 < 90 -> chineseFem.random()
            d100 < 95 -> exoticMale.random()
            else -> exoticFem.random()
        }

        return SendMessage()
            .setChatId(update.message.chatId)
            .setText(name)
            .setReplyMarkup(inlineReplyKeyboard)
    }

    private fun randomName(): String{
        val d100 = Random.nextInt(100)

        return when{
            d100 < 25 -> englishMale.random()
            d100 < 50 -> englishFem.random()
            d100 < 55 -> frenchMale.random()
            d100 < 60 -> frenchFem.random()
            d100 < 65 -> germanMale.random()
            d100 < 70 -> germanFem.random()
            d100 < 75 -> japaneseMale.random()
            d100 < 80 -> japaneseFem.random()
            d100 < 85 -> chineseMale.random()
            d100 < 90 -> chineseFem.random()
            d100 < 95 -> exoticMale.random()
            else -> exoticFem.random()
        }
    }

    override fun processCallback(callbackQuery: CallbackQuery) {

        val name = when(callbackQuery.data){

            "/random_name" -> randomName()
            "/random_name_eng" -> if(Random.nextBoolean()) englishMale.random() else englishFem.random()
            "/random_name_fra" -> if(Random.nextBoolean()) frenchMale.random() else frenchFem.random()
            "/random_name_ger" -> if(Random.nextBoolean()) germanMale.random() else germanFem.random()
            "/random_name_jap" -> if(Random.nextBoolean()) japaneseMale.random() else japaneseFem.random()
            "/random_name_chi" -> if(Random.nextBoolean()) chineseMale.random() else chineseFem.random()
            "/random_name_exotic" -> if(Random.nextBoolean()) exoticMale.random() else exoticFem.random()

            else -> return
        }

        sender.execute(
            EditMessageText()
                .setChatId(callbackQuery.message.chatId)
                .setMessageId(callbackQuery.message.messageId)
                .setText(callbackQuery.message.text)
                .setReplyMarkup(InlineKeyboardMarkup())
        )

        sender.execute(
            SendMessage()
                .setChatId(callbackQuery.message.chatId)
                .setText(name)
                .setReplyMarkup(inlineReplyKeyboard)
        )
    }
}
